# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-09 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ostrich', '0004_status_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='light',
            name='broken',
            field=models.BooleanField(default=0),
        ),
    ]
