# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-09 21:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ostrich', '0005_light_broken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='light',
            old_name='broken',
            new_name='active',
        ),
    ]
