# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-09 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ostrich', '0006_auto_20190309_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='light',
            name='operating',
            field=models.BooleanField(default=1),
        ),
    ]
